name: Linux, gcc, gnu-efi

on: 
  push:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '!set_grub_cpu.cmd'
      - '**.md'
      - '**.sh'
      - '!set_grub_cpu.sh'
      - '**.txt'
      - '**.vbs'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '.gitattributes'
      - '**.cmd'
      - '!set_grub_cpu.cmd'
      - '**.md'
      - '**.sh'
      - '!set_grub_cpu.sh'
      - '**.txt'
      - '**.vbs'

env:
  LOONGARCH64_TOOLCHAIN_TAG: 2025.08.08
  LOONGARCH64_TOOLCHAIN_NAME: x86_64-cross-tools-loongarch64-binutils_2.45-gcc_15.1.0-glibc_2.42.tar.xz

jobs:
  build:
    runs-on: ubuntu-26.04

    strategy:
      matrix:
        arch: [x64, ia32, aa64, riscv64, loongarch64]
        include:
        - arch: x64
          pkg: gcc-mingw-w64-x86-64
          tuple: x86_64-w64-mingw32-
        - arch: ia32
          pkg: gcc-mingw-w64-i686
          tuple: i686-w64-mingw32-
        - arch: aa64
          pkg: gcc-aarch64-linux-gnu
          tuple: aarch64-linux-gnu-
        - arch: riscv64
          pkg: gcc-riscv64-linux-gnu
          tuple: riscv64-linux-gnu-
        - arch: loongarch64
          pkg: gcc-multilib
          tuple: loongarch64-unknown-linux-gnu-

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v7
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Install gcc toolchain
      run: |
        sudo apt-get update
        sudo apt-get install ${{ matrix.pkg }}
        if [[ "${{ matrix.arch }}" == "loongarch64" ]]; then
          curl -L -O https://github.com/loongson/build-tools/releases/download/${LOONGARCH64_TOOLCHAIN_TAG}/${LOONGARCH64_TOOLCHAIN_NAME}
          tar -xJf ${LOONGARCH64_TOOLCHAIN_NAME}
          echo "$PWD/cross-tools/bin" >> "$GITHUB_PATH"
        fi

    - name: Patch GRUB
      run: |
        cd grub
        git apply ../0001-GRUB-fixes.patch
        cd ..

    - name: Patch gnu-efi
      run: |
        cd gnu-efi
        git apply ../0001-gnu-efi-fixes.patch
        cd ..

    - name: Build drivers
      run: make ARCH=${{ matrix.arch }} CROSS_COMPILE=${{ matrix.tuple }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      if: ${{ github.event_name == 'push' }}
      with:
        name: gcc_gnu-efi_${{ matrix.arch }}
        path: src/*.efi

  merge-artifacts:
    runs-on: ubuntu-26.04
    needs: build
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v7
        with:
          name: gcc_gnu-efi
          delete-merged: true

  tests:
    runs-on: ubuntu-26.04
    needs: merge-artifacts

    strategy:
      matrix:
        arch: [x64, ia32, aa64, riscv64, loongarch64]
        include:
        - arch: x64
          pkg: qemu-system-x86-hwe
          qemu_arch: x86_64
          qemu_opts: -M q35
          fw_base: OVMF
        - arch: ia32
          pkg: qemu-system-x86-hwe
          qemu_arch: i386
          qemu_opts: -M pc
          fw_base: OVMF
        - arch: aa64
          pkg: qemu-system-arm-hwe
          qemu_arch: aarch64
          qemu_opts: -M virt -cpu cortex-a57
          fw_base: AAVMF
        - arch: riscv64
          pkg: qemu-system-riscv-hwe
          qemu_arch: riscv64
          qemu_opts: -M virt,pflash0=pflash0 -cpu rva23s64
          fw_base: QEMU_EFI
        - arch: loongarch64
          pkg: qemu-system-misc-hwe
          qemu_arch: loongarch64
          qemu_opts: -M virt -cpu la464
          fw_base: QEMU_EFI

    steps:
    - name: Set up Linux environment
      run: |
        sudo apt-get update
        sudo apt-get -y --no-install-recommends install ${{ matrix.pkg }}

    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Download artifacts
      uses: actions/download-artifact@v8
      with:
        name: gcc_gnu-efi
        path: image/

    - name: Download UEFI firmware
      run: |
        fw_arch=$(echo ${{ matrix.arch }} | tr a-z A-Z)
        fw_zip=${{ matrix.fw_base }}-${fw_arch}.zip
        curl -O https://efi.akeo.ie/${{ matrix.fw_base }}/${fw_zip}
        7z x ${fw_zip}
        rm ${fw_zip}

    - name: Download UEFI Shell
      run: |
        mkdir -p ./image/efi/boot
        curl -L https://github.com/pbatard/UEFI-Shell/releases/download/26H2/shell${{ matrix.arch }}.efi -o ./image/efi/boot/boot${{ matrix.arch }}.efi

    - name: Run tests
      run: |
        export UEFI_ARCH=${{ matrix.arch }}
        if [ "$UEFI_ARCH" = "riscv64" ]; then
          export QEMU_CMD="qemu-system-${{ matrix.qemu_arch }} ${{ matrix.qemu_opts }} -nodefaults -nographic -serial stdio -net none -L . -blockdev node-name=pflash0,driver=file,read-only=on,filename=${{ matrix.fw_base }}.fd -drive format=raw,file=fat:rw:image,id=drv1,if=none -device virtio-blk-device,drive=drv1"
        elif [ "$UEFI_ARCH" = "loongarch64" ]; then
          export QEMU_CMD="qemu-system-${{ matrix.qemu_arch }} ${{ matrix.qemu_opts }} -nodefaults -nographic -serial stdio -net none -L . -bios ${{ matrix.fw_base }}.fd -drive format=raw,file=fat:rw:image"
        else
          export QEMU_CMD="qemu-system-${{ matrix.qemu_arch }} ${{ matrix.qemu_opts }} -nodefaults -nographic -serial stdio -net none -L . -drive if=pflash,format=raw,unit=0,file=${{ matrix.fw_base }}.fd,readonly=on -drive format=raw,file=fat:rw:image"
        fi
        ./tests/run_tests.sh
